name: mkdocs update
on:
  push:
    branches: [ master ]
  pull_request:
    types: [closed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: 123.57.73.246
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: echo hello 
